#!/bin/bash
pacman -Syu --noconfirm 
sudo pacman -S --noconfirm cinnamon gnome-terminal
sudo pacman -S --noconfirm xorg lightdm lightdm-gtk-greeter
systemctl enable lightdm
systemctl enable NetworkManager
echo DONE