#!/bin/bash
sudo pacman -Syu --noconfirm 
sudo pacman -S --noconfirm xorg xorg-server
sudo pacman -S --noconfirm gnome networkmanager
sudo systemctl enable gdm.service
systemctl enable NetworkManager.service
echo DONE