#!/bin/bash
sudo pacman -Syu --noconfirm
sudo pacman -S --noconfirm xorg xorg-server
sudo pacman -S --noconfirm mate mate-extra
sudo pacman -S --noconfirm lightdm
git clone https://aur.archlinux.org/lightdm-slick-greeter.git
cd lightdm-slick-greeter
makepkg -sri
